# Generated by Django 4.0.4 on 2022-04-30 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('PR', 'Paraná'), ('SP', 'São Paulo'), ('RJ', 'Rio de Janeiro'), ('MT', 'Mato Grosso'), ('SC', 'Santa Catarina')], default=('RJ', 'Rio de Janeiro'), max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(help_text='Digite seu nome completo', max_length=50, verbose_name='Nome')),
                ('idade', models.DateField(verbose_name='Data de nascimento')),
                ('email', models.EmailField(max_length=100)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.cidade')),
            ],
        ),
    ]
