# Generated by Django 4.0.5 on 2022-09-22 23:17

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_effect_element_equipment_alter_cidade_estado_warrior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='rarity',
            field=models.CharField(choices=[('B', 'Tier B'), ('A', 'Tier A'), ('S', 'Tier S'), ('SS', 'Tier SS'), ('SSS', 'Tier SS+')], default=('S', 'Tier S'), max_length=3),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
